name: test-wallet
on: [push, workflow_dispatch]
jobs:
  drive:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: subosito/flutter-action@v1
    - run: flutter test
    - run: flutter build web
    - name: Pushes to web repository
      uses: cpina/github-action-push-to-another-repository@main
      env: 
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source-directory: 'build/web'
        destination-github-username: 'pdyason'
        destination-repository-name: 'wallet-web'
        user-email: PDyason
        target-branch: main
