name: test-wallet
on: [push, workflow_dispatch]
jobs:
  drive:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: subosito/flutter-action@v1
    - run: flutter test
    - run: flutter build web
    - name: Pushes to web repository
      uses: tech-thinker/push-to-repo@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        user-name: "github-actions"
        user-email: github-actions@users.noreply.github.com
        source-directory: "build/web"
        destination-github-username: "pdyason"
        destination-repository-name: "wallet-web"
        target-branch: main
