name: test-wallet
on: [push, workflow_dispatch]
jobs:
  drive:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: subosito/flutter-action@v1
    - run: flutter test
    - run: flutter build web
    - run: cd build
    - run: cd web
    - run: git config --global user.email "actions@github.com"
    - run: git config --global user.name "GitHub Actions"
    - run: git init
    - run: git remote add origin https://github.com/pdyason/wallet-web.git
    - run: git add .
    - run: git commit -m "Deployment"
    - run: git push --force --set-upstream origin master